paginate: 5
permalink: pretty
exclude:
- Rakefile
- README.md
- ext
- Gemfile
- Gemfile.lock
- deploy.log
markdown: kramdown
kramdown:
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_tab_width: 2
    coderay_css: class
