name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-ci
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update && \
          apt-get install -y --no-install-recommends \
           ed \
           rsync \
           sqlite3
      - name: Install cobalt
        run: |
          .forgejo/workflows/crate-ci.sh --git cobalt-org/cobalt.rs --crate cobalt

      - name: Show dependencies
        run: |
          set -x
          uv --version
          rustc --version
          cobalt --version
          sqlite3 --version

      - name: Build website
        run: |
          make build index

      - name: Deploy to host
        run: |
          keyfile=$(mktemp)
          echo "${{ secrets.SSH_KEY }}" > "$keyfile"
          export SSH_COMMAND="ssh -i $keyfile -o 'StrictHostKeyChecking no'"

          rsync -avr --delete -e "$SSH_COMMAND" _site/ jer@fnordig.de:fnordig.de/
          rsync -avr --delete -e "$SSH_COMMAND" blog.db jer@fnordig.de:blogsearch/
